### ISSUE TITLE
Node binary not found

### ISSUE THREAD

**Issue by p3k** [TheSavior/SublimeJSCSFormatter#13]
When trying to format a JS file with the formatter I get this alert:

```
Couldn't find Node.js. Make sure it's in your $PATH by running `node -v` in your command-line.
```

However:

``` sh
⚡  node -v
v0.12.0
⚡  which node
/opt/local/bin/node
⚡  echo $PATH | grep /opt/local/bin
/opt/local/bin:/opt/local/sbin…
```

Any ideas?

**Comment by elicwhite** [comment]
The issue is due to it not being visible from the python environment path. There are some default paths set in the settings file. I would recommend changing it there and seeing if it works.

However, there is apparently a bug currently with modifying the settings files... See #11 for more information.

**Comment by p3k** [comment]
Thanks for the swift reply. I have seen #11 already, because trying to edit the settings was my first thought :smirk_cat:
