### ISSUE TITLE
Consider committing jscs to plugin instead of global

### ISSUE THREAD

**Issue by mrjoelkemp** [TheSavior/SublimeJSCSFormatter#2]
I did this for https://github.com/mrjoelkemp/Dependents and it works well. 

This gives us the power to control updates and deliver autofix enhancements without users lifting a finger. 

Try npm dedup before checking in though.

**Comment by elicwhite** [comment]
The big reason I wanted to use the global one is because SublimeLinter requires that as well and I wouldn't want two main JSCS sublime plugins to be using different versions of JSCS.

I could imagine a case where a rule is changed and the linter is modified which causes different errors to be reported, but the autoformatter hasn't updated to the same version.

But mostly, anyone who is using this is almost guaranteed to also be using the SublimeLinter package which means they already have the global.

**Comment by mrjoelkemp** [comment]
Very good point.
