### ISSUE TITLE
Relative .jscsrc files? 

### ISSUE THREAD

**Issue by indexzero** [TheSavior/SublimeJSCSFormatter#8]
I depend on a styleguide module that includes my `.jscsrc` for my automatically so it can be shared between projects. Is there a way to specify this file via a relative path to the project root?

**Comment by elicwhite** [comment]
This JSCS Formatter uses whatever configuration file JSCS would traditionally use when linting that file.

[This issue](https://github.com/jscs-dev/node-jscs/issues/1106) over at JSCS might be discussing what you would like to have. I know I want it. :)

**Comment by indexzero** [comment]
@TheSavior not quite. I actually want to just specify the value passed to `-c` when running `jscs`. e.g. This is more or less what I run now:

```
jscs file.js -c ./node_modules/my-styleguide/.jscsrc --fix
```

**Comment by elicwhite** [comment]
Ah. So if that issue was solved, you could put a .jscsrc file in the root of your project that extends from the node_modules package. It seems like that would then give you the behavior that you want. 

Do you use SublimeLinter-JSCS? How do you handle the configuration file for that?

**Comment by indexzero** [comment]
I could do that in theory, but I just don't want a `.jscsrc` file in my project at all since the `.jscsrc` file in my styleguide _is exactly_ the desired rules. 

I was playing around with it tonight when you sent it out to the jscs mailing list, I was able to get it working by copying my `.jscsrc` from my styleguide, but it's suboptimial right now. An additional option for the jscs file would be super helpful in the cases where it is in a non-standard location like this.

**Comment by elicwhite** [comment]
Do you use SublimeLinter-JSCS? How do you handle the configuration file for that?

From my initial searching, it looks like that doesn't support custom locations for the config files. Since that is such a widely used package, I'm hesitant to diverge from the settings / locations of where SublimeLinter-JSCS would find things.

**Comment by qikkeronline** [comment]
I'd like to second this request :+1: 

We often have all things related to build tools (among those is our .jscsrc file) in a seperate subfolder of the project ('development' or so). Would be great if we could point to this file via the .sublime-project file or something along those lines.

**Comment by elicwhite** [comment]
@qikkeronline, Does your team use SublimeLinter-JSCS? How do you handle configuration of that plugin with a .jscsrc file that isn't in the root?

**Comment by mrjoelkemp** [comment]
@TheSavior Seems to me like supporting a custom config location in the plugin's settings and then adding that to https://github.com/TheSavior/SublimeJSCSFormatter/blob/0cf0f16612d4b20b31029299cc5858484766d130/JSCS-Formatter.py#L71 would suffice.

Folks would then just set that setting to `./node_modules/my-styleguide/.jscsrc`.

This unfortunately means that you'll get requests to support new CLI options down the road, but only a subset of them, I imagine.

**Comment by elicwhite** [comment]
@mrjoelkemp, The big issue I have with doing that is that I don't believe you can do such a thing with SublimeLinter-JSCS and that is pretty much **the** JSCS package for Sublime Text. It doesn't seem like this formatter should be doing anything different than the linter, and should work out of the box if the linter works.

I do definitely want to support style guides that are node modules that define the .jscsrc file, however I believe that it is on node-jscs to support that. Supporting it there would enable it to work for both SublimeLinter-JSCS and JSCS-Formatter as well as anything else that comes along.

FWIW, I'm not putting my foot down and saying no, I just want to make we make the most reasonable decision for the JSCS community as a whole. If this ends up being the thing that makes the most sense, then of course we can add it.

**Comment by mrjoelkemp** [comment]
Agreed. Supporting this now will introduce a setting variable that will have to be deprecated in the future. Of course, users filing issues about this now should warrant either including a setting to supply a custom config location, or quickly implementing that issue in JSCS. 

Within JSCS, that issue would likely result in a minor bump (unless you can convince the team to consider it in a patch version). As such, it's unlikely that the fix would even get released quickly (they wouldn't ship 1.13 with just one new commit). Also, all affected users would have to then manually bump their local jscs version (perhaps not a big obstacle for many).

Both options considered, I'd vote for the plugin setting.

**Comment by elicwhite** [comment]
I agree with your understanding of the JSCS project. To confirm, by implementing this as a sublime plugin setting, we are helping people use this project such that they would be unable to use the larger, more popular package, SublimeLinter-JSCS. Correct?

**Comment by mrjoelkemp** [comment]
I'm not following how the formatter's settings have anything to do with
sublime linter-jscs. The two seem independent to me. Any clarification is
appreciated.

**Comment by elicwhite** [comment]
SublimeLinter-JSCS is a more popular package and has been around significantly longer than this one. SublimeLinter-JSCS to the best of my knowledge does not let people configure via the plugin where it looks for a .jscsrc file or .jscs.json file. It simply lets jscs use its default behavior to find one.

People who have their .jscsrc files in other node_modules, or in subfolders, or other possible locations are the ones requesting this custom feature in the plugin. Since SublimeLinter-JSCS does custom configuration locations, that means that people using this plugin with that setup are not using SublimeLinter-JSCS. 

My goal for this project has been to keep it working as similarly as possible to SublimeLinter-JSCS since I imagine everyone who wishes to use JSCS-Formatter are also using that. By supporting a custom configuration location here, we are diverging from how SublimeLinter-JSCS works. It seems like the **correct** solution would be a solution that enables this use case for both SublimeLinter-JSCS **and** JSCS-Formatter. The only consistent solution I've been able to come up with for that is for JSCS core to implement plugin / `extends` functionality.

I understand that it is unlikely to be a quick addition to JSCS core, so I am entertaining the idea of temporarily allowing a custom setting for the config file location.

The kinds of responses I would like to hear from people using this plugin and are in favor of this plugin supporting custom configuration locations are the following:

> I don't use SublimeLinter-JSCS, and I wouldn't use it even if it did support custom setting locations. However, I **do** want to use JSCS-Formatter
> 
> @TheSavior, you are misunderstanding. SublimeLinter-JSCS does indeed support custom configuration locations and that is what we are using. You should also implement it in JSCS-Formatter.

@mrjoelkemp Does that better communicate my hesitation to adding this functionality to this plugin?

**Comment by mrjoelkemp** [comment]
> It seems like the correct solution would be a solution that enables this use case for both SublimeLinter-JSCS and JSCS-Formatter.

Are they not receptive to adding autofix support? The project doesn't look very responsive to issues or PRs. 

> My goal for this project has been to keep it working as similarly as possible to SublimeLinter-JSCS since I imagine everyone who wishes to use JSCS-Formatter are also using that.

Noble, but the more important goal is to expose key formatter functionality of JSCS within the Sublime Text editor and allow users to use that functionality. You could always roll functionality into SublimeLinter-JSCS at a later time if you so choose. Users would opt-in to using the new setting, so I understand your hesitation but don't agree.

With the growing popularity of projects like ferross/standard, I imagine more and more users would have their config files tucked within node_modules.

**Comment by elicwhite** [comment]
SublimeLinter doesn't want to have their packages doing more than linting. I'm not proposing we also update SublimeLinter-JSCS to support custom config paths, I'm suggesting that it needs to be solved above the sublime package level in JSCS proper so that all of the use cases that require custom config file locations work, not just one plugin in one editor. :-/

I'm going to look into the plugin model for JSCS a little bit more. Storing the .jscsrc file in a node module is something our team is trying to do as well and maybe my understanding of this issue will all shake out as we are doing that.

**Comment by qikkeronline** [comment]
@TheSavior I'm using grunt-jscs (https://github.com/jscs-dev/grunt-jscs), and here you can point to a .jscsrc file via the config as described here: http://grunt-tasks.com/grunt-jscs/ 

It requires manual correcting of your mistakes (it just throws errors) - that's also why I am keen on using SublimeJSCSFormatter. But some of our projects require different rules, and therefor I'd like to have the option to point to a .jscsrc file inside the projects repo :-)

**Comment by elicwhite** [comment]
@qikkeronline, cool. So just to try to articulate my understanding of the problem your team is facing.

You guys have a style guide repo (contains the .jscsrc file), and multiple project repos (that want to use the style guide repo's .jscsrc). You guys use grunt-jscs in the project repos and have that config path pointing to the style guide repo.

And people on your team are using SublimeText and want to be using SublimeJSCSFormatter, but are **not** using SublimeLinter-JSCS as well.

Is that all correct?

**Comment by qikkeronline** [comment]
Hi @TheSavior no - it's a bit more straight forward (but your case could be a valid use case as well):

We have a project dependant .jscsrc file (usually in the same folder as our gruntfile etc), that resides inside the project's repo. Some of ours devs have other preferences as I do, so we leave them to make their own style choices. Hence the project dependant .jscsrc file. We use grunt-jscs on the project repo and have that config path pointing to the .jscsrc file inside the same repo.

This is correct: "And people on your team are using SublimeText and want to be using SublimeJSCSFormatter, but are not using SublimeLinter-JSCS as well."

**Comment by elicwhite** [comment]
Ah, but you don't keep the Gruntfile and jscsrc file in the root of the project? It is in a subfolder? Any particular reason why you guys don't want it at the root?

**Comment by lnfnunes** [comment]
> So just to try to articulate my understanding of the problem your team is facing.
> 
> You guys have a style guide repo (contains the .jscsrc file), and multiple project repos (that want to > use the style guide repo's .jscsrc). You guys use grunt-jscs in the project repos and have that > config path pointing to the style guide repo.
> 
> And people on your team are using SublimeText and want to be using SublimeJSCSFormatter, but are not using SublimeLinter-JSCS as well.
> 
> Is that all correct?

@TheSavior This use case works for me and I agree with this approach. It´s common to grunt-projects have options like .jshintrc, .csslintrc implemented... having a .jscrc whould be great too! [+1]

**Comment by elicwhite** [comment]
Alright, there is enough interest here that I will get around to it at some point. I would also gladly accept a pull request for this.

**Comment by gerbenvandijk** [comment]
Awesome, thanks!
